spring.application.name=workout-tracker-api
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/workout_tracker
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
spring.jpa.hibernate.ddl-auto=validate